/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import entities.Consumidor;
import entities.Pedido;
import entities.Prestador;
import entities.Servico;
import entitiesdb.ConsumidorDB;
import entitiesdb.PedidoDB;
import entitiesdb.PrestadorDB;
import entitiesdb.ServicoDB;

/**
 *
 * @author johnr
 */
public class TelaSolicitarServico extends javax.swing.JFrame {

    /**
     * Creates new form TelaSolicitarServico
     */
    public TelaSolicitarServico() {
        initComponents();
        PrestadorDB pdao= new PrestadorDB();
        for(Prestador p:pdao.listar()){
            
            cbPrestadores.addItem(p);
            
        }
        ConsumidorDB cdao= new ConsumidorDB();
        for(Consumidor c:cdao.listar()){
            
            cbConsumidores.addItem(c);
            
        }
        
    }
    
     private int obterIdPrestadorSelecionado() {
         Prestador prestadorSelecionado = (Prestador) cbPrestadores.getSelectedItem();
        if (prestadorSelecionado != null) {
            return prestadorSelecionado.getId();
        } else {
            // Lidar com a situação em que nenhum item está selecionado
            return -1; // Ou outro valor padrão apropriado
        }
    }
    
    private int obterIdConsumidorSelecionado() {
         Consumidor consumidorSelecionado = (Consumidor) cbConsumidores.getSelectedItem();
        if (consumidorSelecionado != null) {
            return consumidorSelecionado.getId();
        } else {
            // Lidar com a situação em que nenhum item está selecionado
            return -1; // Ou outro valor padrão apropriado
        }
    }
    
    private int obterIdServicoSelecionado() {
         Servico servicoSelecionado = (Servico) cbServicos.getSelectedItem();
        if (servicoSelecionado != null) {
            return servicoSelecionado.getId();
        } else {
            // Lidar com a situação em que nenhum item está selecionado
            return -1; // Ou outro valor padrão apropriado
        }
    }
       
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbPrestadores = new javax.swing.JComboBox<>();
        cbConsumidores = new javax.swing.JComboBox<>();
        cbServicos = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtNomePet = new javax.swing.JTextField();
        txtRacaPet = new javax.swing.JTextField();
        txtTipoPet = new javax.swing.JTextField();
        cadastrarbtn = new javax.swing.JButton();
        txtEstadoServico = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtPortePet1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        cbPrestadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPrestadoresActionPerformed(evt);
            }
        });

        cbServicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbServicosActionPerformed(evt);
            }
        });

        jLabel1.setText("Prestador");

        jLabel2.setText("Consumidor");

        jLabel3.setText("Serviço");

        jLabel5.setText("nome do pet");

        jLabel6.setText("raça do pet");

        jLabel7.setText("tipo do pet");

        jLabel8.setText("estado serviço");

        cadastrarbtn.setText("Proximo");
        cadastrarbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarbtnActionPerformed(evt);
            }
        });

        jLabel9.setText("porte do pet");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtNomePet)
                        .addComponent(cbConsumidores, 0, 117, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel7)
                        .addComponent(cbPrestadores, 0, 117, Short.MAX_VALUE)
                        .addComponent(txtTipoPet))
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbServicos, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(txtEstadoServico, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtRacaPet, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(txtPortePet1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(118, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cadastrarbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(270, 270, 270))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbConsumidores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbPrestadores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbServicos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEstadoServico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNomePet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTipoPet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRacaPet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPortePet1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(28, 28, 28)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addComponent(cadastrarbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbServicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbServicosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbServicosActionPerformed

    private void cbPrestadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPrestadoresActionPerformed
        
        ServicoDB sdao= new ServicoDB();
        cbServicos.removeAllItems();
        for(Servico s:sdao.listarServicosPorPrestador(obterIdPrestadorSelecionado())){
            
            cbServicos.addItem(s);
            
        }
    }//GEN-LAST:event_cbPrestadoresActionPerformed

    private void cadastrarbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarbtnActionPerformed
        int temp1 = obterIdConsumidorSelecionado();
        int temp2 = obterIdPrestadorSelecionado();
        int temp3 = obterIdServicoSelecionado();
        Pedido p = new Pedido();
        PedidoDB dao = new PedidoDB();
        p.setNomePet(txtNomePet.getText());
        p.setTipoPet(txtTipoPet.getText());
        p.setRacaPet(txtRacaPet.getText());
        p.setPortePet(txtPortePet1.getText());
        p.setEstadopedido(txtEstadoServico.getText());
        p.setConsumidorId(temp1);
        p.setPrestadorId(temp2);
        p.setServicoId(temp3);
        dao.create(p);

        txtNomePet.setText("");
        txtTipoPet.setText("");
        txtRacaPet.setText("");
        txtEstadoServico.setText("");
        txtPortePet1.setText("");
        
        TelaProdutosAdicionados tela = new TelaProdutosAdicionados();
        tela.setVisible(true);
    }//GEN-LAST:event_cadastrarbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaSolicitarServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaSolicitarServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaSolicitarServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaSolicitarServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaSolicitarServico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cadastrarbtn;
    private javax.swing.JComboBox<Object> cbConsumidores;
    private javax.swing.JComboBox<Object> cbPrestadores;
    private javax.swing.JComboBox<Object> cbServicos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtEstadoServico;
    private javax.swing.JTextField txtNomePet;
    private javax.swing.JTextField txtPortePet1;
    private javax.swing.JTextField txtRacaPet;
    private javax.swing.JTextField txtTipoPet;
    // End of variables declaration//GEN-END:variables
}
