/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import entities.Pedido;
import entities.ProdutosUsados;
import entitiesdb.PedidoDB;
import entitiesdb.ProdutoUsadoDB;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author johnr
 */
public class TelaInformaçõesGeraisServicoPrestado extends javax.swing.JFrame {

    /**
     * Creates new form TelaInformaçõesGeraisServicoPrestado
     */
    public TelaInformaçõesGeraisServicoPrestado() {
        initComponents();
        listarJTabela();
        listarJTabela1();
        listarJTabela2();
        PedidoDB pdao= new PedidoDB();
        for(Pedido p:pdao.listar()){
            
            cbPedidos.addItem(p);
            
        }
    }
    
    private int obterIdPedidoSelecionado() {
        Pedido pedidoSelecionado = (Pedido) cbPedidos.getSelectedItem();
        if (pedidoSelecionado != null) {
            return pedidoSelecionado.getId();
        } else {
            // Lidar com a situação em que nenhum item está selecionado
            return -1; // Ou outro valor padrão apropriado
        }
    }
    
    public void listarJTabela() {
        DefaultTableModel modelo = (DefaultTableModel) jtListaProdutos.getModel();
        modelo.setNumRows(0);  
        ProdutoUsadoDB pdao = new ProdutoUsadoDB();

        for (ProdutosUsados atual : pdao.listarProdutosUsadosPorPedido(obterIdPedidoSelecionado())) {
            
            modelo.addRow(new Object[]{
                atual.getNome(),
                atual.getQuantidade(),
                atual.getPreco(),
            });

        }

    }
      public void listarJTabela1() {
          DefaultTableModel modelo = (DefaultTableModel) jtGeral.getModel();
        modelo.setNumRows(0);  
        
            int idPedido = obterIdPedidoSelecionado();
        
            PedidoDB pdao = new PedidoDB();
            for (Pedido atual : pdao.listarPedidosPorId(idPedido)) {

                modelo.addRow(new Object[]{
                    atual.getConsumidor(),
                    atual.getPrestador(),
                    atual.getNomePet(),
                    atual.getEstadopedido(),
                    atual.getData(),
                });

            }

        }
        public void listarJTabela2() {
            DefaultTableModel modelo = (DefaultTableModel) jtServico.getModel();
            modelo.setNumRows(0);  
            
            int idPedido = obterIdPedidoSelecionado();
                     
            PedidoDB pdao = new PedidoDB();

            for (Pedido atual : pdao.listarPedidosPorId(idPedido)) {

                modelo.addRow(new Object[]{
                    atual.getServico(),
                    atual.getServicovalor(),
                });

            }

        }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtInformacoesGerais = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        cbPedidos = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtListaProdutos = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jtGeral = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        jtServico = new javax.swing.JTable();
        txtTotalValor = new javax.swing.JLabel();

        jtInformacoesGerais.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "produto", "qntd", "valor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtInformacoesGerais);

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        cbPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPedidosActionPerformed(evt);
            }
        });

        jLabel1.setText("PEDIDOS");

        jtListaProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "produto", "qntd", "valor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jtListaProdutos);

        jtGeral.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "nome", "prestador", "nomepet", "estadopedido", "data"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jtGeral);

        jtServico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "serviço", "valor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(jtServico);

        txtTotalValor.setText("jLabel2");
        txtTotalValor.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                txtTotalValorAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 306, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(208, 208, 208))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(cbPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(197, 197, 197)))
                        .addComponent(txtTotalValor, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 688, Short.MAX_VALUE)
                    .addComponent(jScrollPane4)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtTotalValor, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPedidosActionPerformed
        ProdutoUsadoDB.listarProdutosPorPedido(obterIdPedidoSelecionado());
        listarJTabela();
        listarJTabela1();
        listarJTabela2();
        
        PedidoDB pedido = new PedidoDB();

        int pedidoId = obterIdPedidoSelecionado();


        double valorTotalPedido = pedido.calcularValorTotalPedido(pedidoId);
        System.out.println("Valor Total do Pedido: " + valorTotalPedido);


        double valorServicoPedido = pedido.obterValorServicoDoPedido(pedidoId);
        System.out.println("Valor do Serviço do Pedido: " + valorServicoPedido);
        

        String valorTotalPedidoStr = String.format("%.2f", valorTotalPedido);
        String textoTotal = valorTotalPedidoStr;

        txtTotalValor.setText(textoTotal);
    }//GEN-LAST:event_cbPedidosActionPerformed

    private void txtTotalValorAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_txtTotalValorAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalValorAncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInformaçõesGeraisServicoPrestado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInformaçõesGeraisServicoPrestado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInformaçõesGeraisServicoPrestado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInformaçõesGeraisServicoPrestado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInformaçõesGeraisServicoPrestado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Object> cbPedidos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jtGeral;
    private javax.swing.JTable jtInformacoesGerais;
    private javax.swing.JTable jtListaProdutos;
    private javax.swing.JTable jtServico;
    private javax.swing.JLabel txtTotalValor;
    // End of variables declaration//GEN-END:variables
}
